# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  issues:
    types: [ opened,reopened ]
  pull_request:
    types: [ opened,reopened ]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "needs-triage,bug"
          ignore-if-assigned: false

      - name: Label test
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "need-test"
          ignore-if-assigned: false
